<?php
declare(strict_types=1);

namespace App\Models;

use FlatLeap\LeapModel;

/**
 * Auto-generated by gen.php from FaltLeap
 * Table: public.reverseproxies
 * @property int $idreverseproxies
 * @property string|null $server_name
 * @property string|null $target_address
 * @property string|null $target_port
 * @property bool $generate_ssl
 * @property string|null $custom_configs
 * @property bool $is_websocket
 * @property int $idusers
 * @property string|\DateTimeInterface $acme_valid_until
 */
class Reverseproxies extends LeapModel
{
    /** @var string */
    public string $table = 'reverseproxies';

    /** @var string Schema name */
    public string $schema = 'public';

    /** @var string Primary key column */
    public string $pk = 'idreverseproxies';

    /** @var array<string, array{type:string,primary:bool,null:bool,default:mixed,extra:mixed}> */
    public array $cols = [
  'idreverseproxies' => 
  [
    'type' => 'int',
    'primary' => true,
    'null' => false,
    'default' => 'nextval(\'reverseproxies_idreverseproxies_seq\'::regclass)',
    'extra' => 'identity',],
  'server_name' => 
  [
    'type' => 'string',
    'primary' => false,
    'null' => false,
    'default' => NULL,
    'extra' => NULL,],
  'target_address' => 
  [
    'type' => 'string',
    'primary' => false,
    'null' => false,
    'default' => NULL,
    'extra' => NULL,],
  'target_port' => 
  [
    'type' => 'string',
    'primary' => false,
    'null' => false,
    'default' => NULL,
    'extra' => NULL,],
  'generate_ssl' => 
  [
    'type' => 'bool',
    'primary' => false,
    'null' => true,
    'default' => 'true',
    'extra' => NULL,],
  'custom_configs' => 
  [
    'type' => 'string',
    'primary' => false,
    'null' => true,
    'default' => NULL,
    'extra' => NULL,],
  'is_websocket' => 
  [
    'type' => 'bool',
    'primary' => false,
    'null' => true,
    'default' => 'false',
    'extra' => NULL,],
  'idusers' => 
  [
    'type' => 'int',
    'primary' => false,
    'null' => true,
    'default' => NULL,
    'extra' => NULL,],
  'acme_valid_until' => 
  [
    'type' => 'datetime',
    'primary' => false,
    'null' => true,
    'default' => NULL,
    'extra' => NULL,],
];

    public function __construct($id = null)
    {
        parent::__construct($id);
    }

    public function getTableName(): string
    {
        return 'reverseproxies';
    }

    public function getSchemaName(): string
    {
        return 'public';
    }

    public function getFullTableName(): string
    {
        return 'public.reverseproxies';
    }
}
