<?php
declare(strict_types=1);

namespace App\Models;

use FlatLeap\LeapModel;

/**
 * Auto-generated by gen.php from FaltLeap
 * Table: public.users
 * @property int $idusers
 * @property string|null $username
 * @property string|null $password
 * @property string|null $email
 * @property string|\DateTimeInterface $createdate
 * @property bool $deleted
 */
class Users extends LeapModel
{
    /** @var string */
    public string $table = 'users';

    /** @var string Schema name */
    public string $schema = 'public';

    /** @var string Primary key column */
    public string $pk = 'idusers';

    /** @var array<string, array{type:string,primary:bool,null:bool,default:mixed,extra:mixed}> */
    public array $cols = [
  'idusers' => 
  [
    'type' => 'int',
    'primary' => true,
    'null' => false,
    'default' => 'nextval(\'users_idusers_seq\'::regclass)',
    'extra' => 'identity',],
  'username' => 
  [
    'type' => 'string',
    'primary' => false,
    'null' => false,
    'default' => NULL,
    'extra' => NULL,],
  'password' => 
  [
    'type' => 'string',
    'primary' => false,
    'null' => false,
    'default' => NULL,
    'extra' => NULL,],
  'email' => 
  [
    'type' => 'string',
    'primary' => false,
    'null' => false,
    'default' => NULL,
    'extra' => NULL,],
  'createdate' => 
  [
    'type' => 'datetime',
    'primary' => false,
    'null' => true,
    'default' => 'now()',
    'extra' => NULL,],
  'deleted' => 
  [
    'type' => 'bool',
    'primary' => false,
    'null' => true,
    'default' => 'false',
    'extra' => NULL,],
];

    public function __construct($id = null)
    {
        parent::__construct($id);
    }

    public function getTableName(): string
    {
        return 'users';
    }

    public function getSchemaName(): string
    {
        return 'public';
    }

    public function getFullTableName(): string
    {
        return 'public.users';
    }
}
